### ISSUE TITLE
unable to make it work with laravel 5.4

### ISSUE THREAD

**Issue by neonexxa** [vtalbot/markdown#24]
Call to undefined method Illuminate\Foundation\Application::share()

**Comment by nonoesp** [comment]
I did a pull request two months ago (see https://github.com/vtalbot/markdown/pull/22) that fixes this.

As it hasn't been accepted, I'm using my own repo as a dependency on my projects.

You can see the repo is at https://github.com/nonoesp/markdown

**Comment by neonexxa** [comment]
thanks i manage to get it work
